In [1]:
import numpy as np

In [2]:
student_gpas = np.array([
    [4.0, 3.286, 3.5, 4.0],
    [3.2, 3.8, 4.0, 4.0],
    [3.96, 3.92, 4.0, 4.0]
], np.float16)

student_gpas

array([[4.   , 3.285, 3.5  , 4.   ],
       [3.2  , 3.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)

In [3]:
student_gpas.ndim

2

In [4]:
student_gpas.shape

(3, 4)

In [5]:
student_gpas.size

12

## About data types

In [6]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [7]:
%whos

Variable        Type       Data/Info
------------------------------------
np              module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
student_gpas    ndarray    3x4: 12 elems, type `float16`, 24 bytes
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [8]:
study_minutes[0] = 150

In [9]:
first_day_minutes = study_minutes[0]

In [10]:
first_day_minutes

150

In [11]:
type(first_day_minutes)

numpy.uint16

In [12]:
study_minutes[1] = 60

In [13]:
study_minutes[2:6] = [80, 60, 30, 90]

## Multidimensional Arrays (Creation and Indexing)

In [14]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])

In [15]:
study_minutes.shape

(2, 100)

In [16]:
study_minutes[1][0] = 60

In [17]:
study_minutes[1, 0] # => study_minutes[(1, 0)]

60

In [18]:
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [19]:
fake_log[[3, 8]]

array([44, 50], dtype=uint16)

index = np.array([
    [3, 8],
    [0, 1]
])
fake_log[index]

In [20]:
study_minutes = np.append(study_minutes, [fake_log], axis=0)

In [21]:
study_minutes[1, 1] = 360

## Boolean Array Indexing

In [22]:
fake_log[fake_log < 60]

array([44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52, 31,
       57, 37, 58], dtype=uint16)

In [23]:
np.array([True, True, False]) & np.array([True, False, False])

array([ True, False, False])

In [24]:
study_minutes[(study_minutes < 60) & (study_minutes > 0)]

array([30, 44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52,
       31, 57, 37, 58], dtype=uint16)

In [25]:
study_minutes[study_minutes < 60] = 0

In [26]:
study_minutes[2]

array([132, 122, 128,   0, 136, 129, 101,  95,   0, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
         0, 106, 117,   0,  98,  67, 121, 159,  81, 170,   0,   0,   0,
        87, 179,   0, 116, 177, 118,  78, 171, 117,  88, 123, 102,   0,
        79,   0, 108,  80,   0, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,   0, 102, 113,   0, 131, 161, 118,  82,  89,  81,   0,
        81,   0, 119,   0,  82,   0, 159,   0, 113,  71, 121, 140,  91,
        70,   0, 106,  64, 127, 110,   0,  93,  79], dtype=uint16)

## Slicing

In [28]:
practice = np.arange(42)
practice.shape = (7, 6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [29]:
practice[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
practice[2:5, 3]

array([15, 21, 27])

In [31]:
practice[2:5, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

In [32]:
# Any Slicing in ndarray returns a view not a copy
not_copied = practice[:]
not_copied[1, 1] = 90201
practice, not_copied

(array([[    0,     1,     2,     3,     4,     5],
        [    6, 90201,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[    0,     1,     2,     3,     4,     5],
        [    6, 90201,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))

In [39]:
practice.base is None # Becoz it is not copied

True

In [34]:
not_copied.base is None # Becoz it is copied as a view

False

In [36]:
not_copied.base is practice

True

In [40]:
practice.flags['OWNDATA'], not_copied.flags['OWNDATA']

(True, False)